import = ["$HOME/World/alacritty-theme/themes/tokyo-night.toml"]
[env]
# Set terminal to alacritty to get most of it
term="alacritty"

[window]
  option_as_alt="OnlyLeft"
  decorations="full"


# Add some padding, so the text is visible clearly
[window.padding]
  x = 1
  y = 1

[scrolling]
  history = 100000

[font]
  size = 12.0

[font.normal]
  family = "DejaVu Sans Mono"
  style = "Book"


[font.bold]
  family = "DejaVu Sans Mono"
  style = "Bold"

[font.italic]
  family = "DejaVu Sans Mono"
  style = "Oblique"

[font.bold_italic]
  family = "DejaVu Sans Mono"
  style = "Bold Oblique"

[cursor]
  style = "Block"
